### ISSUE TITLE
RxJava

### ISSUE THREAD

**Issue by Sergey26Tarasenko** [ed-george/AndroidVimeoExtractor#10]
When will library on RxJava?

**Comment by ed-george** [comment]
Hi @GREKSTAR - I will look into creating RxJava Bindings for this but feel free to make a pull request if you so wish

**Comment by GREKSTAR** [comment]
Perhaps this library will help you. Thanks for the answer!

[https://github.com/Commit451/YouTubeExtractor?utm_source=android-arsenal.com&utm_medium=referral&utm_campaign=3700](url)

**Comment by ed-george** [comment]
Thanks for raising, but as of March 2023 this repo is now read-only. There will be no further updates
