### ISSUE TITLE
Android method goes to failure section

### ISSUE THREAD

**Issue by GajanandGuptaAndroid** [ed-george/AndroidVimeoExtractor#12]
Hello sir,
when i am passing video url ( https://vimeo.com/222900263/61c8627300) which containing two id then method goes to failure section .
please resolve this issue and sir check my video url which is playing on browser but your method goes to 

 @Override
            public void onFailure(Throwable throwable) {
                //Error handling here
            }

this section. please resolve Asap.

**Comment by ed-george** [comment]
Hi @GajanandGuptaAndroid - thanks for reporting your issue.

I am afraid I am unlikely going to be able to look at this in the immediate future, but I will attempt to fix this in any future release. Please feel free to fork the library and make a PR if applicable.

**Comment by GajanandGuptaAndroid** [comment]
Hi sir,
     i am using compile 'com.github.ed-george:AndroidVimeoExtractor:1.0.0'
 that dependency in android studio if u have any latest updated versing of
gradle then inform me sir asap.

**Comment by ed-george** [comment]
[The latest version is 1.1.1](https://jitpack.io/#ed-george/AndroidVimeoExtractor/1.1.1), please click that link or edit your `build.gradle` file to reflect this

**Comment by GajanandGuptaAndroid** [comment]
Hi sir,

i am getting that message  : {"message":"Because of its privacy settings,
this video cannot be played here.","title":"Sorry","view":7}

My video url: https://vimeo.com/222900263/61c8627300  but playing on
browser   and when using vimeo extractor going to failure section.

Please resolve this asap.

Thanks

**Comment by ed-george** [comment]
@GajanandGuptaAndroid as I said in my previous message I am unlikely to be looking at this in the immediate future. Again, please do feel free to fork the library and make a PR if applicable.
