### ISSUE TITLE
Difference between the official API

### ISSUE THREAD

**Issue by klaszlo8207** [ed-george/AndroidVimeoExtractor#14]
What is the difference?

https://github.com/vimeo/vimeo-networking-java

**Comment by ed-george** [comment]
This library gives you access to MP4 links for any (_most_) video(s) to allow you to natively playback a video in a player of your choice  - which is not possible AFAIK in the official java lib.

**Comment by klaszlo8207** [comment]
So if I use this api, than VIMEO can ban me/or my android app or not? I think Vimeo Lib do the same like this, just with credentials (KEY-SECRET pair):)
This lib is very easy.

**Comment by ed-george** [comment]
As stated in the README file, please only use this library at your own risk after accepting and acknowledging the [Vimeo Terms of Service](https://vimeo.com/terms).

**Comment by klaszlo8207** [comment]
Thanks!
