### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by otopba** [ed-george/AndroidVimeoExtractor#18]
Hi!
Could you create a new release please?  

I want to get this changes https://github.com/ed-george/AndroidVimeoExtractor/commit/d1e242ec966268a921af72437e3024bf1da876b4

Thank you!

**Comment by ed-george** [comment]
Hi there, the changes should be in 1.2.0, are you not seeing that behaviour?

**Comment by otopba** [comment]
Commit was on Dec 26, 2018
![image](https://user-images.githubusercontent.com/4225279/53594712-839c8f00-3bac-11e9-95aa-3b56c16ea4b7.png)
But release was on on 17 Dec 2018 
![image](https://user-images.githubusercontent.com/4225279/53594753-96af5f00-3bac-11e9-80c8-c9fe00ee0d5b.png)
So there are no changes there =)

**Comment by ed-george** [comment]
@otopba I have created a [new release](https://github.com/ed-george/AndroidVimeoExtractor/releases/tag/1.2.0) please let me know if that fixes your issue

**Comment by otopba** [comment]
Hmm
com.github.ed-george:AndroidVimeoExtractor:1.2.0 don't have last changes
but
com.github.ed-george:AndroidVimeoExtractor:-SNAPSHOT contains it

Something wrong with release =/

**Comment by ed-george** [comment]
@otopba Looks to be an issue with Jitpack, so I have releases 1.2.1 to try and bring everything back in sync. Let me know if that helps

**Comment by otopba** [comment]
@ed-george Yes, it works. Thank you very much!

**Comment by ed-george** [comment]
Perfect, sorry about the confusion @otopba - I will close this ticket now 👍 Thanks for using my library
