### ISSUE TITLE
Facebook account kit sdk does not work if I add library

### ISSUE THREAD

**Issue by saidurcse** [ed-george/AndroidVimeoExtractor#19]
When I add **implementation 'com.github.ed-george:AndroidVimeoExtractor:1.2.1'**

After when I signed the apk then facebook account kit sdk does not work. It gives error "a system error occurred".

**Comment by ed-george** [comment]
Can you please provide some more details? A crash report or at least a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by saidurcse** [comment]
Reproduction path:

1) After adding below account kit library. Facebook login works fine.
`**implementation 'com.facebook.android:account-kit-sdk:5.+'**`

2) Now if I add below your AndroidVimeoExtractor library. Vimeo video is working fine but facebook account kit stopped working.
`**compile 'com.github.ed-george:AndroidVimeoExtractor:<latest-version>' (1.2.1)**`

After adding AndroidVimeoExtractor library, Facebook account kit does not crash. It gives error message like "**a system issue occurred. please try again**". Again if I remove your AndroidVimeoExtractor library, Facebook account kit works fine.

**Note**: I can not share with you the code because this is official private project and confidential.

**Comment by ed-george** [comment]
Can you run `./gradlew :app:dependencies` and supply the output?
