### ISSUE TITLE
Privarte video always return 403

### ISSUE THREAD

**Issue by omfg74** [ed-george/AndroidVimeoExtractor#22]
When I try to watch private video it returned 403 error only

**Comment by ed-george** [comment]
Hi @omfg74 - are you able to provide an example of this?

**Comment by omfg74** [comment]
Do you need an axample of code or video from vimeo?

**Comment by ed-george** [comment]
Both would be ideal - thanks

**Comment by ed-george** [comment]
Closing due to no response
