### ISSUE TITLE
VimeoVideo class needs improvement

### ISSUE THREAD

**Issue by mathiasleimhofer** [ed-george/AndroidVimeoExtractor#27]
Currently the class VimeoVideo can only parse videos that have a progressive stream, but it would be a good idea to improve this to switch between the provided hls, dash or progressive streams, some videos don't provide progressive video streams.

**Comment by mathiasleimhofer** [comment]
Currently: 
//Access video stream information
JSONArray streamArray = requestJson.getJSONObject("request")
    .getJSONObject("files")
    .getJSONArray("progressive");

Should be like: 
//Access video stream information
JSONArray streamArray = requestJson.getJSONObject("request")
    .getJSONObject("files")
    .getJSONArray(streamType);

**Comment by ed-george** [comment]
Thanks for raising, but as of March 2023 this repo is now read-only. There will be no further updates
