### ISSUE TITLE
N/W Preferred url and thumb

### ISSUE THREAD

**Issue by Jagruttam** [ed-george/AndroidVimeoExtractor#4]
Hi, @ed-george and @ravidsrk 
I am also developer so I can understand the efforts you did.
Just a suggestion.
Your library will be more sweet if you provide url/thumb logic based on network speed.

Like, on 2G: Light, on 3G: Medium, on 4G/WiFi: High

```
String prefThumb = vimeoVideo.getNWPreferredThumb();
String prefUrl = vimeoVideo.getNWPreferredUrl();
```

> Thanks!

**Comment by ed-george** [comment]
Whilst this is a nice idea, I think it might be slightly out of scope for the library.

From my research, the Vimeo API does not consistently return the same thumbnail and video attributes for each video and is solely dependant on how the video was uploaded and the nature of its resolution. I _could_ see some benefit in these types of methods, but given the ever changing nature of the Vimeo API (I believe they added 4K video not too long ago), I could not guarantee any methods I create would be future proofed.  

Finally the methods, such as those you describe, would almost certainly use the `android.permission.ACCESS_NETWORK_STATE` permission which is currently not part of the library. I would prefer to keep the permissions used by the library to the bare minimum at this time, so I will not look to be adding this functionality.

**Comment by Jagruttam** [comment]
@ed-george liked your approach,

> I would prefer to keep the permissions used by the library to the bare minimum at this time

Awesome!
