### ISSUE TITLE
Referer Issue

### ISSUE THREAD

**Issue by jhpassion0621** [ed-george/AndroidVimeoExtractor#5]
Thanks for your good library. But I found one issue in your library. It has "Referer" header name spell wrong. Of course your spell is right but http has spell issue so I think we should follow their issue :)
Http uses wrong spell "Referer" so we need to use "Referer" too. Please update soon. Thanks!

**Comment by ed-george** [comment]
Thank you @jhpassion0621 for spotting this - This has now been amended and is included in version 1.1.1
