### ISSUE TITLE
403 error with private video

### ISSUE THREAD

**Issue by amin234** [ed-george/AndroidVimeoExtractor#6]
i tried this identifier private video "156225003" but it return  403 although with same library in ios <https://github.com/lilfaf/YTVimeoExtractor>   it works well and return direct url :(

**Comment by Adel2p** [comment]
i face the same problem

**Comment by ed-george** [comment]
Hi, @amin234 and @Adel2p - I have not been able to replicate the issue you are both facing. If you could supply me with an example of the code that is failing to get private video information that would be great.

For private videos, you are best to try not passing in a referrer (see https://github.com/lilfaf/YTVimeoExtractor/issues/30) with the request

**Comment by Adel2p** [comment]
thanks for your reply 
this sample of code :_
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        VimeoExtractor.getInstance().fetchVideoWithIdentifier("156225003", null, new OnVimeoExtractionListener() {
            @Override
            public void onSuccess(VimeoVideo video) {
                String hdStream = video.getStreams().get("540p");
                //...
            }

            @Override
            public void onFailure(Throwable throwable) {
                //Error handling here
   
            }
        });
    }
it returns 403 error

**Comment by ed-george** [comment]
@Adel2p using version 1.1.1 of this library I am able to see all relevant information for this video - so I am afraid I cannot replicate this. 

Can you please paste the error message you see and confirm which version of the library you are using.

**Comment by Adel2p** [comment]
thank you 
its work well now
