### ISSUE TITLE
Not working on pure android nougat for some videos.

### ISSUE THREAD

**Issue by parinparikh-nv** [ed-george/AndroidVimeoExtractor#9]
This library works awesome but facing some issues in pure android nougat version of android.Is any one have solution about this problem?
Thank you.

**Comment by ed-george** [comment]
HI @parinparikh-nv can you please provide me with some details of videos that are not working, the code you are using or any error messages you are seeing

**Comment by ed-george** [comment]
@parinparikh-nv As you have not provided any further information I will mark this issue as closed.

Should you be able to replicate this, please provide adequate background detail to allow others to replicate the issue you are facing.
